/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'

// Create/Update Routes

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRoute,
} as any)

const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)

const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(marketing)': {
      id: '/(marketing)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRoute
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRouteImport
    }
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module './routes/(marketing)/route' {
  const createFileRoute: CreateFileRoute<
    '/(marketing)',
    FileRoutesByPath['/(marketing)']['parentRoute'],
    FileRoutesByPath['/(marketing)']['id'],
    FileRoutesByPath['/(marketing)']['path'],
    FileRoutesByPath['/(marketing)']['fullPath']
  >
}
declare module './routes/dashboard' {
  const createFileRoute: CreateFileRoute<
    '/dashboard',
    FileRoutesByPath['/dashboard']['parentRoute'],
    FileRoutesByPath['/dashboard']['id'],
    FileRoutesByPath['/dashboard']['path'],
    FileRoutesByPath['/dashboard']['fullPath']
  >
}
declare module './routes/docs' {
  const createFileRoute: CreateFileRoute<
    '/docs',
    FileRoutesByPath['/docs']['parentRoute'],
    FileRoutesByPath['/docs']['id'],
    FileRoutesByPath['/docs']['path'],
    FileRoutesByPath['/docs']['fullPath']
  >
}
declare module './routes/auth/$pathname' {
  const createFileRoute: CreateFileRoute<
    '/auth/$pathname',
    FileRoutesByPath['/auth/$pathname']['parentRoute'],
    FileRoutesByPath['/auth/$pathname']['id'],
    FileRoutesByPath['/auth/$pathname']['path'],
    FileRoutesByPath['/auth/$pathname']['fullPath']
  >
}
declare module './routes/(marketing)/index' {
  const createFileRoute: CreateFileRoute<
    '/(marketing)/',
    FileRoutesByPath['/(marketing)/']['parentRoute'],
    FileRoutesByPath['/(marketing)/']['id'],
    FileRoutesByPath['/(marketing)/']['path'],
    FileRoutesByPath['/(marketing)/']['fullPath']
  >
}

// Create and export the route tree

interface marketingRouteRouteChildren {
  marketingIndexRoute: typeof marketingIndexRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingIndexRoute: marketingIndexRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof marketingIndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
}

export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/': typeof marketingIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/(marketing)/': typeof marketingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/docs' | '/auth/$pathname'
  fileRoutesByTo: FileRoutesByTo
  to: '/dashboard' | '/docs' | '/auth/$pathname' | '/'
  id:
    | '__root__'
    | '/(marketing)'
    | '/dashboard'
    | '/docs'
    | '/auth/$pathname'
    | '/(marketing)/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
}

const rootRouteChildren: RootRouteChildren = {
  marketingRouteRoute: marketingRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  AuthPathnameRoute: AuthPathnameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(marketing)",
        "/dashboard",
        "/docs",
        "/auth/$pathname"
      ]
    },
    "/(marketing)": {
      "filePath": "(marketing)/route.tsx",
      "children": [
        "/(marketing)/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/docs": {
      "filePath": "docs.tsx"
    },
    "/auth/$pathname": {
      "filePath": "auth/$pathname.tsx"
    },
    "/(marketing)/": {
      "filePath": "(marketing)/index.tsx",
      "parent": "/(marketing)"
    }
  }
}
ROUTE_MANIFEST_END */
